### ISSUE TITLE
Does not work inside v-for

### ISSUE THREAD

**Issue by purplekrayons** [rawilk/vue-context#29]
Note that I am using **vue-context** version **4.0.2**.

This component will fail when used inside of a v-for loop. Per Vue's [documentation on ref](https://vuejs.org/v2/api/#ref):

> When used on elements/components with v-for, the registered reference will be an Array containing DOM nodes or component instances.

I have attempted to get around the issue by using a method `openMenu`.

```vue
<ul>
    <li v-for="item in items" :key="item.index">
        <vs-button @contextmenu.prevent="openMenu(item.index)">{{item.label}}</vs-button>
        <vue-context ref="menu" :data="item.index">
            <ul>
                <li @click="unpinItem(item.index)">Unpin</li>
            </ul>
        </vue-context>
    </li>
</ul>
```

```js
methods: {
    openMenu(itemIndex) {
        for (const [index, VueComponent] of this.$refs.menu.entries()) {
            if (VueComponent.$attrs.data === itemIndex) {
                this.$refs.menu[index].open();
                break;
            }
        }
    },
    unpinItem(itemIndex) {
        this.$store.dispatch('unpinItem', {
            index: itemIndex,
        });
    },
}
```

However, I get a couple errors when I try and fire the `open` event `this.$refs.menu[index].open();`

> Error in nextTick: "TypeError: Cannot read property 'clientY' of undefined"
> TypeError: Cannot read property 'clientY' of undefined

I was reading through your [advanced documentation](https://vue-context.com/docs/4.0/advanced-usage), but I see no mention of using this context menu inside of a v-for loop.

How do you recommend this be handled?

**Comment by rawilk** [comment]
@purplekrayons You need to send the event through to the menu as well when you open it. You would need to write something like this:

```html
<vs-button @contextmenu.prevent="openMenu($event, item.index)">{{item.label}}</vs-button>
```

```js
openMenu(event, itemIndex) {
       for (const [index, VueComponent] of this.$refs.menu.entries()) {
            if (VueComponent.$attrs.data === itemIndex) {
                this.$refs.menu[index].open(event);
                break;
            }
        }
}
```

That should work, although I normally wouldn't use the menu in a loop like that. Since the menu accepts a data object as its second argument for the `open` method, I would just create one instance of the menu and send whatever item, or in your case it looks like you just need the index, to the menu and handle it from there.

You're also trying to pass `data` in as a prop to the menu but it isn't a prop so that wouldn't work. Like I mentioned earlier, you just need to send the data as a second argument to the open method and then you can reference it via a slot scope. You also don't need to add a `ul` tag inside the menu since by default it renders with a `ul` tag as the root element. You can of course change this with the `tag` prop if needed.

Also, when you use a ref in a v-for like that, it usually helps to also put `ref-in-for` on the tag as well (`vue-context ref="menu" ref-in-for>`)

**Comment by purplekrayons** [comment]
Hey mate, I appreciate the clarification. I've ended up doing as you suggested as it definitely makes more sense. Thank you.

```vue
<li v-for="item in items" :key="item.index">
    <vs-button @contextmenu.prevent="$refs.menu.open($event, { index: client.index })">
        {{item.label}}
    </vs-button>
</li>
<vue-context ref="menu">
    <template slot-scope="child">
        <li @click.prevent="unpinClient($event.target, child.data)">Unpin</li>
    </template>
</vue-context>
```

```js
methods: {
    unpinClient(event, child) {
        this.$store.dispatch('unpinClient', {
            index: child.index, // client id to remove
        });
    },
}
```
