### ISSUE TITLE
Big bundle size due to core-js

### ISSUE THREAD

**Issue by 2-5** [rawilk/vue-context#33]
Using `vue-context` increases bundle size by 41 KB (gzipped). It seems tree-shaking is not working properly, and the whole `core-js` in bundled in, not just the two functions used.

**Comment by rawilk** [comment]
That makes sense, I'll be updating the menu later and this dependency will be removed in favor of local polyfills.

**Comment by 2-5** [comment]
The problem is not fixed, the bundle size is still 36 KB (gzipped).

![2019-10-12_134509](https://user-images.githubusercontent.com/3753822/66701675-4bd2f980-ecee-11e9-84e8-1bf2c143e0d5.png)

Looking more carefully inside `vue-context/dist/js/vue-context.js`, I can see that it has the Vue runtime in there.

**Comment by rawilk** [comment]
To be honest, I'm really not worried about a 36 KB size.

**Comment by tripflex** [comment]
@rawilk why i def appreciate you releasing this library, that's 36KB gzip minified (which not everything supports gzip) -- so minified is around 101kb in size:
https://bundlephobia.com/result?p=vue-context@4.1.1

While I understand you may not be worried about it, there may be others who do (just wanted to mention that).

For those that do, my recommendation would be to use webpack chunking/code-splitting to only load it when needed (async):
https://webpack.js.org/guides/code-splitting/

Unfortunately because this lib does not just export `VueContext` as default, you have to do it like this:
```javascript
components: {
  VueContext: async () => {
    const instance = await import( /* webpackChunkName: "vue-context" */  'vue-context' )
    return instance.VueContext
  }
},
```

When any other lib that exports as default, could just be like this:
```javascript
SomeLibComponent: () => import( /* webpackChunkName: "some-lib-component" */  'some-lib-component' ),
```

If you're not familiar with code splitting yet, i strongly recommend reading and learning more about it, as this will allow you to keep bundle size small and async load resources as they are needed (to not cause delay on initial page load)

Now that 4.1+ doesn't include the CSS i'm going to have to figure out how to deal with this as well :-\

**Comment by tripflex** [comment]
I'm still trying to figure out why the dist version of this lib is 100kb+ when i build it from source, it's only around ~17kb ... so i would say if anything, import the source into your own project if you have all the webpack handling setup -- my guess is there's a lot of bloat in the released dist version

**Comment by rawilk** [comment]
@tripflex Good point. I think I'm not going to build it anymore and leave that part of it to you instead. I think that should help sizes.
