### ISSUE TITLE
Unable to pass data from the contextmenu.

### ISSUE THREAD

**Issue by PlainBane** [rawilk/vue-context#7]
### Description
Hello,
I'm unable to pass data from the contextmenu, taken from the advanced usage part in usage examples.
I don't get any errors, but console log returns undefined.
### Steps to Reproduce

1. [Take code from the advanced usage section.]
2. [Run Vue app]
3. [Check console output]

**Expected behavior:** [Debug console to return value 'foo'.]

**Actual behavior:** [Console returns undefined.]

### Additional Information

I'm using vue-context as Nuxt plugin. Everything works great, but this one feature.
I'm also using _template slot-scope="child"_ instead of  _template scope="child"_

**Comment by rawilk** [comment]
I've never used nuxt, but from what I've found, there's nothing in my component that should be causing the data to be undefined.

Are you sure your data is set before it is sent to the context menu with the `open` function?

Also, which version of `vue-context` are you using? I ask because you mentioned you are using `template slot-scope="child"` instead of `template scope="child"`. Since version **3.0.0**, the docs have stated to use `slot-scope` instead of `scope`. I also dropped the `<template>` part from it as well and put the slot-scope directly on the `ul` tag instead.

**Comment by PlainBane** [comment]
I modified the code to fit your instructions and managed to find the issue. If I copy/paste code from the docs it doesn't work for me.  

`<VueContext ref="menu">`
          `<ul slot-scope="child">`
             `<li @click="onClick($event.target.innerText, child.data)">Option1</li> // Returns "foo"` 
             `<li @click="onClick($event.target.innerText, child.userData)">Option2</li> //Returns undefined`
          `</ul>`
   `</VueContext>`

It seems that it needs _child.data_ insted of _child.userData_. Thank you for your help and quick response.
